export { default as Hero } from './Hero'
export { default as Inspiration } from './Inspiration'
export { default as HowItWorks } from './HowItWorks'
export { default as FinalCTA } from './FinalCTA'
export { default as Footer } from './Footer'